BEGIN;

CREATE TYPE MUSIC_GENRE AS ENUM(
    'PSYCHEDELIC_ROCK', 'PSYCHEDELIC_CLOUD_RAP', 'SOUL', 'POP', 'BRIT_POP'
);

CREATE TABLE IF NOT EXISTS USER_TABLE(
    ID SERIAL PRIMARY KEY,
    USERNAME TEXT UNIQUE NOT NULL,
    SAFE_PASSWORD VARCHAR(90) NOT NULL
);

CREATE TABLE IF NOT EXISTS COORDINATES(
    ID SERIAL PRIMARY KEY,
    X FLOAT NOT NULL CHECK(X > -584),
    Y FLOAT
);

CREATE TABLE IF NOT EXISTS STUDIO(
    ID SERIAL PRIMARY KEY,
    ADDRESS TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS MUSIC_BANDS(
    ID SERIAL PRIMARY KEY,
    BAND_NAME TEXT NOT NULL CHECK(BAND_NAME <> ''),
    COORDINATES_FK INT REFERENCES COORDINATES(ID) ON DELETE CASCADE,
    CREATION_DATE TIMESTAMP NOT NULL,
    NUMBER_OF_PARTICIPANTS BIGINT CHECK(NUMBER_OF_PARTICIPANTS > 0),
    ESTABLISHMENT_DATE TIMESTAMP,
    MUSIC_GENRE MUSIC_GENRE,
    STUDIO_FK INT REFERENCES STUDIO(ID) ON DELETE CASCADE,
    OWNER_ID INT REFERENCES USER_TABLE(ID) ON DELETE CASCADE
);

END;
